# Generated by Django 6.0.5 on 2026-05-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('date_of_birth', models.DateField()),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=10)),
                ('national_id', models.CharField(max_length=20, unique=True)),
                ('address', models.TextField()),
                ('district', models.CharField(max_length=100)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='donors/photos/')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('flagged', 'Flagged — High Risk'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('last_donation_date', models.DateField(blank=True, null=True)),
                ('total_donations', models.PositiveIntegerField(default=0)),
                ('needs_transport', models.BooleanField(default=False)),
                ('transport_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DonationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('donated_at', models.DateField()),
                ('blood_units', models.DecimalField(decimal_places=2, default=0.45, max_digits=4)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('facility', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.facility')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_donations', to=settings.AUTH_USER_MODEL)),
                ('donor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='donations', to='donors.donorprofile')),
            ],
            options={
                'ordering': ['-donated_at'],
            },
        ),
        migrations.CreateModel(
            name='EligibilityChecklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hiv_positive', models.BooleanField(default=False)),
                ('hepatitis_b', models.BooleanField(default=False)),
                ('hepatitis_c', models.BooleanField(default=False)),
                ('malaria_last_3months', models.BooleanField(default=False)),
                ('tuberculosis_active', models.BooleanField(default=False)),
                ('recent_tattoo_6months', models.BooleanField(default=False)),
                ('recent_surgery_6months', models.BooleanField(default=False)),
                ('on_anticoagulants', models.BooleanField(default=False)),
                ('pregnancy_or_breastfeed', models.BooleanField(default=False)),
                ('donated_last_3months', models.BooleanField(default=False)),
                ('weight_below_50kg', models.BooleanField(default=False)),
                ('feels_well_today', models.BooleanField(default=True)),
                ('no_alcohol_last_24h', models.BooleanField(default=True)),
                ('is_auto_flagged', models.BooleanField(default=False)),
                ('flagged_reason', models.TextField(blank=True)),
                ('completed_at', models.DateTimeField(auto_now=True)),
                ('donor', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='eligibility', to='donors.donorprofile')),
            ],
        ),
    ]
