# Generated by Django 6.0.5 on 2026-05-30 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SOSRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_type_needed', models.CharField(choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-'), ('any', 'Any Available')], max_length=5)),
                ('units_needed', models.PositiveSmallIntegerField(default=1)),
                ('patient_condition', models.TextField(help_text='Brief clinical context — no patient names')),
                ('urgency', models.CharField(choices=[('critical', 'Critical — Patient on table'), ('urgent', 'Urgent — Within 1 hour'), ('standard', 'Standard — Within 2 hours')], default='urgent', max_length=20)),
                ('status', models.CharField(choices=[('open', 'Open — Awaiting Response'), ('acknowledged', 'Acknowledged'), ('in_transit', 'Blood In Transit'), ('resolved', 'Resolved'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('resolution_notes', models.TextField(blank=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('is_overdue', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('acknowledged_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_acknowledged', to=settings.AUTH_USER_MODEL)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sos_requests', to=settings.AUTH_USER_MODEL)),
                ('requesting_facility', models.ForeignKey(limit_choices_to={'facility_type': 'clinic'}, on_delete=django.db.models.deletion.CASCADE, related_name='sos_sent', to='accounts.facility')),
                ('target_bank', models.ForeignKey(blank=True, limit_choices_to={'facility_type': 'blood_bank'}, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sos_received', to='accounts.facility')),
            ],
            options={
                'verbose_name': 'SOS Request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SOSStatusUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(max_length=20)),
                ('new_status', models.CharField(max_length=20)),
                ('note', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('sos_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='sos.sosrequest')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
